<a href="https://colab.research.google.com/github/Theosdoor/ML-Summative-2023/blob/main/ML_Coursework.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Dataset](https://archive.ics.uci.edu/dataset/320/student+performance) by Paulo Cortez

Should use classification algorithm because data is discrete (KNN, SVM, random forest, etc.). Use one-hot for categorical data.

Original paper says that G1, G2 correlated to G3 so its harder to predict G3 without them, but much more valuable to do so. Show attempts with and without?

Read these papers:<br>

- [Penalised regression](https://www.semanticscholar.org/paper/Adding-bias-to-reduce-variance-in-psychological-A-Helwig/fefc6557ef19fed43c77c7e89a5e2602f399cb8e)
- [Handling imbalanced data](https://www.semanticscholar.org/paper/A-Wrapper-for-Reweighting-Training-Instances-for-Karagiannopoulos-Anyfantis/ba3c675c188d19616fcecd22dff29656d7019522)
  - naive bayes, decision trees, knn
- [The Latent of Student Learning Analytic with K-mean Clustering for Student Behaviour Classification](https://www.semanticscholar.org/paper/The-Latent-of-Student-Learning-Analytic-with-K-mean-Mansur-Yusof/5dc76919cc24aa3a4bafcc8813f0bb5003af0c2c)



In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split

In [ ]:
df_maths = pd.read_csv('/content/drive/MyDrive/UNI/Computer Science/COMP2261 Artificial Intelligence/Machine Learning Coursework/student-mat-formatted.csv')
df_por = pd.read_csv('/content/drive/MyDrive/UNI/Computer Science/COMP2261 Artificial Intelligence/Machine Learning Coursework/student-por-formatted.csv')
df_por

In [ ]:
X = df_por.drop('G3', axis = 1) # consider whether to include G1, G2
y = df_por['G3']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 42) # test_size too small?

X_train

school sex  age address famsize Pstatus  Medu  Fedu      Mjob      Fjob  \
579     MS   M   18       U     LE3       T     1     3   at_home  services   
211     GP   M   16       R     LE3       T     3     3   teacher     other   
9       GP   M   15       U     GT3       T     3     4     other     other   
612     MS   M   17       R     GT3       T     4     3  services     other   
299     GP   F   20       R     GT3       T     2     1     other     other   
..     ...  ..  ...     ...     ...     ...   ...   ...       ...       ...   
71      GP   M   15       U     GT3       T     4     2     other     other   
106     GP   F   15       U     GT3       T     2     2     other     other   
270     GP   M   16       U     GT3       T     4     4  services  services   
435     MS   F   15       R     LE3       T     1     1   at_home  services   
102     GP   M   15       U     GT3       T     4     4  services     other   

     ... romantic famrel  freetime  goout  Dalc Walc health absences  G1  G2  
579  ...      yes      4         3      3     2    3      3        0   9  10  
211  ...       no      3         3      4     3    5      3       16  10  11  
9    ...       no      5         5      1     1    1      5        0  12  12  
612  ...      yes      4         5      5     1    3      2        4  10  11  
299  ...      yes      1         2      3     1    2      2        8  10  12  
..   ...      ...    ...       ...    ...   ...  ...    ...      ...  ..  ..  
71   ...       no      3         3      3     1    1      3        0  11   9  
106  ...       no      5         1      2     1    1      3        4  10  10  
270  ...       no      5         3      2     1    2      5        4  14  15  
435  ...       no      5         4      3     1    2      4        0  10  10  
102  ...       no      5         3      3     1    1      5        2  12  13  

[454 rows x 32 columns]

In [ ]:
for col in X.columns:
  print(col,'\n',X[col].unique(),'\n')



school 
 ['GP' 'MS'] 

sex 
 ['F' 'M'] 

age 
 [18 17 15 16 19 22 20 21] 

address 
 ['U' 'R'] 

famsize 
 ['GT3' 'LE3'] 

Pstatus 
 ['A' 'T'] 

Medu 
 [4 1 3 2 0] 

Fedu 
 [4 1 2 3 0] 

Mjob 
 ['at_home' 'health' 'other' 'services' 'teacher'] 

Fjob 
 ['teacher' 'other' 'services' 'health' 'at_home'] 

reason 
 ['course' 'other' 'home' 'reputation'] 

guardian 
 ['mother' 'father' 'other'] 

traveltime 
 [2 1 3 4] 

studytime 
 [2 3 1 4] 

failures 
 [0 3 1 2] 

schoolsup 
 ['yes' 'no'] 

famsup 
 ['no' 'yes'] 

paid 
 ['no' 'yes'] 

activities 
 ['no' 'yes'] 

nursery 
 ['yes' 'no'] 

higher 
 ['yes' 'no'] 

internet 
 ['no' 'yes'] 

romantic 
 ['no' 'yes'] 

famrel 
 [4 5 3 1 2] 

freetime 
 [3 2 4 1 5] 

goout 
 [4 3 2 1 5] 

Dalc 
 [1 2 5 3 4] 

Walc 
 [1 3 2 4 5] 

health 
 [3 5 1 2 4] 

absences 
 [ 4  2  6  0 10  8 16 14  1 12 24 22 32 30 21 15  9 18 26  7 11  5 13  3] 

G1 
 [ 0  9 12 14 11 13 10 15 17  8 16 18  7  6  5  4 19] 

G2 
 [11 13 14 12 16 17  8 10 15  9  7  6 18 19 